### ISSUE TITLE
Convert Recip*Ease from React.js to React Native

### ISSUE THREAD

**Issue by sbirvin1s** [sbirvin1s/recip-ease#16]
To support deployment as an app, current use of React.js needs to be refactored to React Native and feature set revised.

Related Sub Tickets:
- [ ] [Research differences between React.js and React Native](https://github.com/sbirvin1s/recip-ease/issues/17)
- [ ] [Create app layout and user flow diagrams in Adobe Xd or Figma](https://github.com/sbirvin1s/recip-ease/issues/18)
  - [ ] [Home page](https://github.com/sbirvin1s/recip-ease/issues/19)
      - [ ] Content of home page
  - [ ] [Add ingredients page](https://github.com/sbirvin1s/recip-ease/issues/20)
  - [ ] [Search Recipes page](https://github.com/sbirvin1s/recip-ease/issues/21)
    - [ ] Add recipes functionality
  - [ ] [Log Food](https://github.com/sbirvin1s/recip-ease/issues/22)
  - [ ] other
- [ ] Implement user authentication

**Comment by sbirvin1s** [comment]
Paused for now due to issues getting dev environment with React Native and Android Studio set up on WSL
